server:
  port: ${ENV_SERVER_PORT:8888}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${ENV_GIT_URI:https://github.com/ucsal/POG-config-repo-cdd}
          default-label: main
          force-pull: ${ENV_FORCE_PULL:true}
          search-paths:
            - "*"

encrypt:
  key: ${ENV_ENCRYPTION_KEY:MinhaChaveSecreta123!}

management:
  endpoints:
    web:
      exposure:
        include:
          - encrypt
          - decrypt
          - refresh
